
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 10 04:14:07 CST 2024
//----------------------------------------------------

package srbn.graphpi.BackEnd.Parser;

import java_cup.runtime.*;
import srbn.graphpi.BackEnd.DomainObjs.Errors.*;
import srbn.graphpi.BackEnd.DomainObjs.Graphs.*;
import java.util.ArrayList;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri May 10 04:14:07 CST 2024
  */
public class Parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Parser() {super();}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\044\000\002\002\004\000\002\002\005\000\002\003" +
    "\007\000\002\003\006\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\005\006\000" +
    "\002\005\004\000\002\007\006\000\002\007\004\000\002" +
    "\006\006\000\002\006\004\000\002\010\006\000\002\010" +
    "\004\000\002\011\010\000\002\011\013\000\002\011\012" +
    "\000\002\011\015\000\002\014\010\000\002\014\013\000" +
    "\002\015\012\000\002\015\017\000\002\015\017\000\002" +
    "\015\025\000\002\013\010\000\002\013\012\000\002\013" +
    "\013\000\002\013\015\000\002\012\010\000\002\012\016" +
    "\000\002\012\013\000\002\012\021\000\002\016\014\000" +
    "\002\017\010" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\243\000\004\036\004\001\002\000\004\004\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\004\040\243\001\002\000\006\004\011\037\012\001" +
    "\002\000\004\040\013\001\002\000\004\002\000\001\002" +
    "\000\004\036\014\001\002\000\012\005\017\006\031\012" +
    "\021\014\024\001\002\000\006\004\ufffa\037\ufffa\001\002" +
    "\000\004\041\232\001\002\000\004\070\221\001\002\000" +
    "\006\004\uffff\037\uffff\001\002\000\004\070\210\001\002" +
    "\000\006\004\ufffb\037\ufffb\001\002\000\006\036\166\041" +
    "\167\001\002\000\004\066\152\001\002\000\006\004\ufffc" +
    "\037\ufffc\001\002\000\006\037\126\041\125\001\002\000" +
    "\006\004\ufffd\037\ufffd\001\002\000\006\033\075\041\076" +
    "\001\002\000\004\070\032\001\002\000\004\033\033\001" +
    "\002\000\004\010\034\001\002\000\004\040\035\001\002" +
    "\000\006\014\037\036\036\001\002\000\004\014\037\001" +
    "\002\000\004\066\063\001\002\000\006\033\041\041\042" +
    "\001\002\000\004\036\051\001\002\000\004\033\043\001" +
    "\002\000\004\013\044\001\002\000\004\071\045\001\002" +
    "\000\004\033\046\001\002\000\004\025\047\001\002\000" +
    "\004\070\050\001\002\000\006\037\uffea\041\uffea\001\002" +
    "\000\004\014\052\001\002\000\004\066\053\001\002\000" +
    "\004\033\054\001\002\000\004\015\055\001\002\000\004" +
    "\066\056\001\002\000\006\012\057\037\060\001\002\000" +
    "\004\070\061\001\002\000\006\033\uffe5\041\uffe5\001\002" +
    "\000\004\037\062\001\002\000\006\033\uffe4\041\uffe4\001" +
    "\002\000\004\033\064\001\002\000\004\015\065\001\002" +
    "\000\004\066\066\001\002\000\006\012\067\037\070\001" +
    "\002\000\004\070\071\001\002\000\006\033\uffe7\041\uffe7" +
    "\001\002\000\004\037\072\001\002\000\006\033\uffe6\041" +
    "\uffe6\001\002\000\006\033\041\041\074\001\002\000\006" +
    "\037\uffeb\041\uffeb\001\002\000\004\005\113\001\002\000" +
    "\010\004\ufff8\033\077\037\ufff8\001\002\000\004\036\100" +
    "\001\002\000\004\007\102\001\002\000\006\004\ufff9\037" +
    "\ufff9\001\002\000\004\070\103\001\002\000\004\033\104" +
    "\001\002\000\004\017\105\001\002\000\004\070\106\001" +
    "\002\000\004\033\107\001\002\000\004\020\110\001\002" +
    "\000\004\070\111\001\002\000\004\037\112\001\002\000" +
    "\006\004\uffdf\037\uffdf\001\002\000\004\070\114\001\002" +
    "\000\004\033\115\001\002\000\004\011\116\001\002\000" +
    "\004\066\117\001\002\000\006\033\120\037\121\001\002" +
    "\000\004\013\122\001\002\000\006\033\uffef\041\uffef\001" +
    "\002\000\004\070\123\001\002\000\004\037\124\001\002" +
    "\000\006\033\uffee\041\uffee\001\002\000\010\004\ufff6\033" +
    "\150\037\ufff6\001\002\000\004\033\127\001\002\000\004" +
    "\036\130\001\002\000\004\006\131\001\002\000\004\070" +
    "\132\001\002\000\004\033\133\001\002\000\004\010\134" +
    "\001\002\000\004\040\135\001\002\000\004\036\136\001" +
    "\002\000\004\014\037\001\002\000\006\033\041\041\140" +
    "\001\002\000\004\037\141\001\002\000\010\033\142\037" +
    "\uffe9\041\uffe9\001\002\000\004\013\143\001\002\000\004" +
    "\071\144\001\002\000\004\033\145\001\002\000\004\025" +
    "\146\001\002\000\004\070\147\001\002\000\006\037\uffe8" +
    "\041\uffe8\001\002\000\004\036\100\001\002\000\006\004" +
    "\ufff7\037\ufff7\001\002\000\004\033\153\001\002\000\004" +
    "\015\154\001\002\000\004\066\155\001\002\000\006\033" +
    "\156\037\157\001\002\000\004\021\160\001\002\000\006" +
    "\036\uffe3\041\uffe3\001\002\000\004\066\161\001\002\000" +
    "\004\033\162\001\002\000\004\013\163\001\002\000\004" +
    "\071\164\001\002\000\004\037\165\001\002\000\006\036" +
    "\uffe2\041\uffe2\001\002\000\004\033\172\001\002\000\010" +
    "\004\ufff2\033\170\037\ufff2\001\002\000\004\036\100\001" +
    "\002\000\006\004\ufff3\037\ufff3\001\002\000\004\014\173" +
    "\001\002\000\004\066\174\001\002\000\004\033\175\001" +
    "\002\000\004\015\176\001\002\000\004\066\177\001\002" +
    "\000\006\033\200\037\201\001\002\000\004\021\202\001" +
    "\002\000\006\036\uffe1\041\uffe1\001\002\000\004\066\203" +
    "\001\002\000\004\033\204\001\002\000\004\013\205\001" +
    "\002\000\004\071\206\001\002\000\004\037\207\001\002" +
    "\000\006\036\uffe0\041\uffe0\001\002\000\004\033\211\001" +
    "\002\000\004\011\212\001\002\000\004\066\213\001\002" +
    "\000\006\033\214\037\215\001\002\000\004\013\216\001" +
    "\002\000\004\041\uffed\001\002\000\004\070\217\001\002" +
    "\000\004\037\220\001\002\000\004\041\uffec\001\002\000" +
    "\004\033\222\001\002\000\004\011\223\001\002\000\004" +
    "\066\224\001\002\000\006\033\225\037\226\001\002\000" +
    "\004\013\227\001\002\000\006\033\ufff1\041\ufff1\001\002" +
    "\000\004\070\230\001\002\000\004\037\231\001\002\000" +
    "\006\033\ufff0\041\ufff0\001\002\000\010\004\ufff4\033\233" +
    "\037\ufff4\001\002\000\004\007\235\001\002\000\006\004" +
    "\ufff5\037\ufff5\001\002\000\004\070\236\001\002\000\004" +
    "\033\237\001\002\000\004\016\240\001\002\000\004\070" +
    "\241\001\002\000\004\037\242\001\002\000\006\004\uffde" +
    "\037\uffde\001\002\000\004\036\244\001\002\000\012\005" +
    "\017\006\031\012\021\014\024\001\002\000\006\004\ufffe" +
    "\037\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\243\000\004\002\004\001\001\000\004\003\007\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\024\004\017\005\026\006\021\007\024" +
    "\010\014\011\027\012\022\014\015\015\025\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\013\037\001\001\000\004\013\072\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\016\100\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\013\136\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\016\150\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\016\170\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\017\233\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\024\004\244\005\026\006" +
    "\021\007\024\010\014\011\027\012\022\014\015\015\025" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




    private ArrayList<ErrorP> errors = new ArrayList<>();
    private ArrayList<Graph> graphs = new ArrayList<>();

    public void syntax_error(Symbol token) {
            if (token.sym != ParserSym.EOF){
            //System.out.println("sintax error: " +token.value + " en la linea " + token.left);
                addError(token, "Sintax error close at: ");
            }
        }

        public void unrecovered_syntax_error(Symbol token) {
            //System.out.println("unrec sintax error: " +token.value + " en la línea " + token.right+" en la columna " + token.left);
            addError(token, "unrec error: ");
        }

        private String removeBrckt(String str){
            return str.replace("[", "").replace("]", "");
        }

        public String removeQuotes(String str){
                return str.replace("\"", "");
            }

        public void addGraph(Graph g){
            graphs.add(g);
        }

        public void addError(Symbol token, String msj) {
            try {
                ArrayList<String> list = new ArrayList<>();
//                for (Integer ex : expected_token_ids()) {
//                    list.add(ParserSym.terminalNames[ex]);
//                }
                errors.add(new ErrorP(token.left, token.right, token.value.toString(), 1, msj, list));
            } catch (Exception e) {

            }
        }

        public ArrayList<ErrorP> getErrors() {
            return errors;
        }

        public ArrayList<Graph> getGraphs() {
            return graphs;
        }


}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Parser$actions {
  private final Parser parser;

  /** Constructor */
  CUP$Parser$actions(Parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Parser$do_action(
    int                        CUP$Parser$act_num,
    java_cup.runtime.lr_parser CUP$Parser$parser,
    java.util.Stack            CUP$Parser$stack,
    int                        CUP$Parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser$result;

      /* select the action based on the action number */
      switch (CUP$Parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // pieChart ::= TITTLE STRING COMMA LEGENDPOSITION STRING CLOSEBRACKET 
            {
              ChartGraph RESULT =null;
		int tittleleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int tittleright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String tittle = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int posleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int posright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String pos = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  RESULT = new ChartGraph(parser.removeQuotes(tittle), parser.removeQuotes(pos));
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("pieChart",13, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // chartGraphs ::= OPENBRACKET TITTLE STRING COMMA XAXISLABEL STRING COMMA YAXISLABEL STRING CLOSEBRACKET 
            {
              ChartGraph RESULT =null;
		int tittleleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int tittleright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		String tittle = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int xLabelleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int xLabelright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String xLabel = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int yLabelleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int yLabelright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String yLabel = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  RESULT = new ChartGraph(parser.removeQuotes(tittle), parser.removeQuotes(xLabel), parser.removeQuotes(yLabel));
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("chartGraphs",12, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-9)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // plotsData ::= plotsData OPENBRACKET COMMA Xaxis NUMBER COMMA Yaxis NUMBER COMMA SIZE NUMBER COMMA COLOR HEXCODE CLOSEBRACKET 
            {
              ArrayList<DataGraph> RESULT =null;
		int pointsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)).left;
		int pointsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)).right;
		ArrayList<DataGraph> points = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-14)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-10)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		String y = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int colleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int colright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String col = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  points.add(new DataGraph(Integer.parseInt(x), Integer.parseInt(y), Integer.parseInt(s), col));
                                                                                    RESULT = points;                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("plotsData",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-14)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // plotsData ::= plotsData OPENBRACKET COMMA Xaxis NUMBER COMMA Yaxis NUMBER CLOSEBRACKET 
            {
              ArrayList<DataGraph> RESULT =null;
		int pointsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)).left;
		int pointsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)).right;
		ArrayList<DataGraph> points = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-8)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String y = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  points.add(new DataGraph(Integer.parseInt(x), Integer.parseInt(y)));
                                                                                    RESULT = points;                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("plotsData",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // plotsData ::= Xaxis NUMBER COMMA Yaxis NUMBER COMMA SIZE NUMBER COMMA COLOR HEXCODE CLOSEBRACKET 
            {
              ArrayList<DataGraph> RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-10)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		String y = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int sleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int colleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int colright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String col = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  ArrayList<DataGraph> data = new ArrayList<>();
                                                                                    data.add(new DataGraph(Integer.parseInt(x), Integer.parseInt(y), Integer.parseInt(s), col));
                                                                                    RESULT = data;                                  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("plotsData",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // plotsData ::= Xaxis NUMBER COMMA Yaxis NUMBER CLOSEBRACKET 
            {
              ArrayList<DataGraph> RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String y = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  ArrayList<DataGraph> data = new ArrayList<>();
                                                                                    data.add(new DataGraph(Integer.parseInt(x), Integer.parseInt(y)));
                                                                                    RESULT = data;                                  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("plotsData",8, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // linePoints ::= linePoints COMMA OPENBRACKET Xaxis NUMBER COMMA Yaxis NUMBER LABEL STRING CLOSEBRACKET 
            {
              ArrayList<DataGraph> RESULT =null;
		int pointsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).left;
		int pointsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).right;
		ArrayList<DataGraph> points = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-10)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String y = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int labelleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int labelright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String label = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  points.add(new DataGraph(Integer.parseInt(x), Integer.parseInt(y), parser.removeQuotes(label)));
                                                                                    RESULT = points;                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("linePoints",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // linePoints ::= linePoints COMMA OPENBRACKET Xaxis NUMBER COMMA Yaxis NUMBER CLOSEBRACKET 
            {
              ArrayList<DataGraph> RESULT =null;
		int pointsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)).left;
		int pointsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)).right;
		ArrayList<DataGraph> points = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-8)).value;
		int xleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String y = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  points.add(new DataGraph(Integer.parseInt(x), Integer.parseInt(y)));
                                                                                    RESULT = points;                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("linePoints",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // linePoints ::= Xaxis NUMBER COMMA Yaxis NUMBER LABEL STRING CLOSEBRACKET 
            {
              ArrayList<DataGraph> RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String y = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int labelleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int labelright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String label = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  ArrayList<DataGraph> data = new ArrayList<>();
                                                                                    data.add(new DataGraph(Integer.parseInt(x), Integer.parseInt(y), parser.removeQuotes(label)));
                                                                                    RESULT = data;                                  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("linePoints",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // linePoints ::= Xaxis NUMBER COMMA Yaxis NUMBER CLOSEBRACKET 
            {
              ArrayList<DataGraph> RESULT =null;
		int xleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int xright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String x = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int yleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int yright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String y = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  ArrayList<DataGraph> data = new ArrayList<>();
                                                                                    data.add(new DataGraph(Integer.parseInt(x), Integer.parseInt(y)));
                                                                                    RESULT = data;                                  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("linePoints",9, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // lineDataDecl ::= lineDataDecl CLOSEBRACKET COMMA OPENBRACKET NAME STRING COMMA POINTS OPENBRACE OPENBRACKET linePoints CLOSEBRACE CLOSEBRACKET COMMA COLOR HEXCODE COMMA LINESTYLE STRING 
            {
              ArrayList<LinealData> RESULT =null;
		int lineDataleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-18)).left;
		int lineDataright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-18)).right;
		ArrayList<LinealData> lineData = (ArrayList<LinealData>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-18)).value;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-13)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-13)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-13)).value;
		int pointsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)).left;
		int pointsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)).right;
		ArrayList<DataGraph> points = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-8)).value;
		int colleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int colright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String col = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int styleleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int styleright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String style = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		  lineData.add(new LinealData(parser.removeQuotes(name), col, parser.removeQuotes(style), points));
                                                                                    RESULT = lineData;                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lineDataDecl",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-18)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // lineDataDecl ::= lineDataDecl CLOSEBRACKET COMMA OPENBRACKET NAME STRING COMMA POINTS OPENBRACE OPENBRACKET linePoints CLOSEBRACE CLOSEBRACKET 
            {
              ArrayList<LinealData> RESULT =null;
		int lineDataleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)).left;
		int lineDataright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)).right;
		ArrayList<LinealData> lineData = (ArrayList<LinealData>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-12)).value;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int pointsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).left;
		int pointsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)).right;
		ArrayList<DataGraph> points = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-2)).value;
		  lineData.add(new LinealData(parser.removeQuotes(name), points));
                                                                                    RESULT = lineData;                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lineDataDecl",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // lineDataDecl ::= NAME STRING COMMA POINTS OPENBRACE linePoints CLOSEBRACE COMMA COLOR HEXCODE COMMA LINESTYLE STRING 
            {
              ArrayList<LinealData> RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-11)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-11)).value;
		int pointsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int pointsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		ArrayList<DataGraph> points = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int colleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int colright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		String col = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int styleleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int styleright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		String style = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		  ArrayList<LinealData> lineData = new ArrayList<>();
                                                                                    lineData.add(new LinealData(parser.removeQuotes(name), col, parser.removeQuotes(style), points));
                                                                                    RESULT = lineData;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lineDataDecl",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-12)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // lineDataDecl ::= NAME STRING COMMA POINTS OPENBRACE OPENBRACKET linePoints CLOSEBRACE 
            {
              ArrayList<LinealData> RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-6)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-6)).value;
		int pointsleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int pointsright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<DataGraph> points = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  ArrayList<LinealData> lineData = new ArrayList<>();
                                                                                    lineData.add(new LinealData(parser.removeQuotes(name), points));
                                                                                    RESULT = lineData;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lineDataDecl",11, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // pieDataDecl ::= LABEL STRING COMMA VALUE NUMBER COMMA COLOR STRING CLOSEBRACKET 
            {
              ArrayList<DataGraph> RESULT =null;
		int labelleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int labelright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		String label = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int colleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int colright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String col = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  ArrayList<DataGraph> data = new ArrayList<>();
                                                                                    data.add(new DataGraph(parser.removeQuotes(label), Integer.parseInt(val), parser.removeQuotes(col)));
                                                                                    RESULT = data;                                  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("pieDataDecl",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // pieDataDecl ::= LABEL STRING COMMA VALUE NUMBER CLOSEBRACKET 
            {
              ArrayList<DataGraph> RESULT =null;
		int labelleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int labelright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String label = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  ArrayList<DataGraph> data = new ArrayList<>();
                                                                                    data.add(new DataGraph(parser.removeQuotes(label), Integer.parseInt(val)));
                                                                                    RESULT = data;                                  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("pieDataDecl",10, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // dataDecl ::= dataDecl COMMA CATEGORY STRING COMMA VALUE NUMBER COMMA COLOR STRING CLOSEBRACKET 
            {
              ArrayList<DataGraph> RESULT =null;
		int barsDataleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).left;
		int barsDataright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)).right;
		ArrayList<DataGraph> barsData = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-10)).value;
		int catleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int catright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		String cat = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int colleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int colright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String col = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  barsData.add(new DataGraph(parser.removeQuotes(cat), Integer.parseInt(val), parser.removeQuotes(col)));
                                                                                    RESULT=barsData;                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("dataDecl",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-10)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // dataDecl ::= dataDecl COMMA CATEGORY STRING COMMA VALUE NUMBER CLOSEBRACKET 
            {
              ArrayList<DataGraph> RESULT =null;
		int barsDataleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int barsDataright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		ArrayList<DataGraph> barsData = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int catleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int catright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String cat = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  barsData.add(new DataGraph(parser.removeQuotes(cat), Integer.parseInt(val)));
                                                                                    RESULT=barsData;                                
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("dataDecl",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // dataDecl ::= CATEGORY STRING COMMA VALUE NUMBER COMMA COLOR STRING CLOSEBRACKET 
            {
              ArrayList<DataGraph> RESULT =null;
		int catleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).left;
		int catright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-7)).right;
		String cat = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-7)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int colleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int colright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String col = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  ArrayList<DataGraph> data = new ArrayList<>();
                                                                                    data.add(new DataGraph(parser.removeQuotes(cat), Integer.parseInt(val), parser.removeQuotes(col)));
                                                                                    RESULT = data;                                  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("dataDecl",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-8)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // dataDecl ::= CATEGORY STRING COMMA VALUE NUMBER CLOSEBRACKET 
            {
              ArrayList<DataGraph> RESULT =null;
		int catleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).left;
		int catright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)).right;
		String cat = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-4)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  ArrayList<DataGraph> data = new ArrayList<>();
                                                                                    data.add(new DataGraph(parser.removeQuotes(cat), Integer.parseInt(val)));
                                                                                    RESULT = data;                                  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("dataDecl",7, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-5)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // plotGraphDecl ::= plotsData CLOSEBRACE 
            {
              PlotGraph RESULT =null;
		int dataleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int dataright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<DataGraph> data = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  RESULT = new PlotGraph(data);
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("plotGraphDecl",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // plotGraphDecl ::= plotsData CLOSEBRACE COMMA chartGraphs 
            {
              PlotGraph RESULT =null;
		int dataleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int dataright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		ArrayList<DataGraph> data = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int chartleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int chartright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ChartGraph chart = (ChartGraph)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		  RESULT = new PlotGraph(data, chart);
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("plotGraphDecl",6, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // pieGraphDecl ::= pieDataDecl CLOSEBRACE 
            {
              PieGraph RESULT =null;
		int dataleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int dataright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<DataGraph> data = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		  RESULT = new PieGraph(data);
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("pieGraphDecl",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // pieGraphDecl ::= pieDataDecl CLOSEBRACE COMMA pieChart 
            {
              PieGraph RESULT =null;
		int dataleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int dataright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		ArrayList<DataGraph> data = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int chartleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int chartright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ChartGraph chart = (ChartGraph)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		  RESULT = new PieGraph(data, chart);
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("pieGraphDecl",4, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // lineGraphDecl ::= lineDataDecl CLOSEBRACE 
            {
              LinealGraph RESULT =null;
		int lineDataleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int lineDataright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<LinealData> lineData = (ArrayList<LinealData>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new LinealGraph(lineData);
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lineGraphDecl",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lineGraphDecl ::= lineDataDecl CLOSEBRACE COMMA chartGraphs 
            {
              LinealGraph RESULT =null;
		int lineDataleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int lineDataright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		ArrayList<LinealData> lineData = (ArrayList<LinealData>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int chartleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int chartright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ChartGraph chart = (ChartGraph)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new LinealGraph(lineData, chart);
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("lineGraphDecl",5, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // barsGraphDecl ::= dataDecl CLOSEBRACE 
            {
              BarsGraph RESULT =null;
		int dataleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int dataright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		ArrayList<DataGraph> data = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		 RESULT = new BarsGraph(data);
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("barsGraphDecl",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // barsGraphDecl ::= dataDecl CLOSEBRACE COMMA chartGraphs 
            {
              BarsGraph RESULT =null;
		int dataleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).left;
		int dataright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)).right;
		ArrayList<DataGraph> data = (ArrayList<DataGraph>)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-3)).value;
		int chartleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int chartright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		ChartGraph chart = (ChartGraph)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 RESULT = new BarsGraph(data, chart);
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("barsGraphDecl",3, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // graphTypes ::= plotGraphDecl 
            {
              Object RESULT =null;
		int plotGraphleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int plotGraphright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		PlotGraph plotGraph = (PlotGraph)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 parser.addGraph(plotGraph);  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("graphTypes",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // graphTypes ::= pieGraphDecl 
            {
              Object RESULT =null;
		int pieGraphleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int pieGraphright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		PieGraph pieGraph = (PieGraph)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 parser.addGraph(pieGraph);   
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("graphTypes",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // graphTypes ::= lineGraphDecl 
            {
              Object RESULT =null;
		int lineGraphleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int lineGraphright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		LinealGraph lineGraph = (LinealGraph)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 parser.addGraph(lineGraph);  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("graphTypes",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // graphTypes ::= barsGraphDecl 
            {
              Object RESULT =null;
		int barsGraphleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).left;
		int barsGraphright = ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()).right;
		BarsGraph barsGraph = (BarsGraph)((java_cup.runtime.Symbol) CUP$Parser$stack.peek()).value;
		 parser.addGraph(barsGraph);  
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("graphTypes",2, ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // graphDecl ::= DATA OPENBRACE OPENBRACKET graphTypes 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("graphDecl",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-3)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // graphDecl ::= graphDecl DATA OPENBRACE OPENBRACKET graphTypes 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("graphDecl",1, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-4)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // graphPi ::= OPENBRACKET graphDecl CLOSEBRACKET 
            {
              Object RESULT =null;

              CUP$Parser$result = parser.getSymbolFactory().newSymbol("graphPi",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-2)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          return CUP$Parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= graphPi EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser$stack.elementAt(CUP$Parser$top-1)).value;
		RESULT = start_val;
              CUP$Parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser$stack.elementAt(CUP$Parser$top-1)), ((java_cup.runtime.Symbol)CUP$Parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser$parser.done_parsing();
          return CUP$Parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

