
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 10 06:14:33 CST 2024
//----------------------------------------------------

package srbn.graphpi.BackEnd.Parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int ASTHERISK = 46;
  public static final int DIVIDE = 47;
  public static final int KEYWORDS = 21;
  public static final int DESCRIPTION = 16;
  public static final int CHART = 20;
  public static final int LEGENDPOSITION = 12;
  public static final int Yaxis = 11;
  public static final int EQUALS = 53;
  public static final int HEXCODE = 63;
  public static final int CATEGORY = 3;
  public static final int GREATER = 55;
  public static final int DOBLEQUOTE = 42;
  public static final int LESS = 56;
  public static final int MINUS = 45;
  public static final int FOR = 30;
  public static final int FONTFAMILY = 25;
  public static final int DATA = 2;
  public static final int SEMICOLON = 34;
  public static final int POINTS = 6;
  public static final int LESSEQUAL = 58;
  public static final int COMMA = 33;
  public static final int Xaxis = 10;
  public static final int DIV = 52;
  public static final int DIFFERENT = 54;
  public static final int DIGIT = 59;
  public static final int PLUS = 44;
  public static final int ASSIGN = 50;
  public static final int SINGLEQUOTE = 43;
  public static final int BACKGROUNDCOLOR = 24;
  public static final int IF = 28;
  public static final int FONTSIZE = 26;
  public static final int CLOSEPARENTHESIS = 41;
  public static final int EOF = 0;
  public static final int LINK = 18;
  public static final int NUMBSIZE = 64;
  public static final int SIZE = 15;
  public static final int error = 1;
  public static final int MUL = 51;
  public static final int CLOSEBRACKET = 37;
  public static final int DOBLEDOT = 35;
  public static final int NUMBER = 60;
  public static final int TITTLE = 5;
  public static final int ICON = 17;
  public static final int NAME = 4;
  public static final int COLOR = 9;
  public static final int GREATEREQUAL = 57;
  public static final int HEADER = 22;
  public static final int OPENPARENTHESIS = 40;
  public static final int DOWHILE = 32;
  public static final int ELSE = 29;
  public static final int LETTER = 61;
  public static final int OPENBRACKET = 36;
  public static final int WHILE = 31;
  public static final int CLOSEBRACE = 39;
  public static final int XAXISLABEL = 13;
  public static final int COPYRIGHT = 27;
  public static final int FOOTER = 23;
  public static final int LINESTYLE = 19;
  public static final int SUM = 48;
  public static final int OPENBRACE = 38;
  public static final int STRING = 62;
  public static final int VALUE = 7;
  public static final int LABEL = 8;
  public static final int SUB = 49;
  public static final int YAXISLABEL = 14;
}

