
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 14 22:19:34 CST 2024
//----------------------------------------------------

package srbn.graphpi.BackEnd.Parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int ASTHERISK = 48;
  public static final int DIVIDE = 49;
  public static final int KEYWORDS = 21;
  public static final int DESCRIPTION = 16;
  public static final int CHART = 20;
  public static final int LEGENDPOSITION = 12;
  public static final int Yaxis = 11;
  public static final int EQUALS = 55;
  public static final int HEXCODE = 65;
  public static final int CATEGORY = 3;
  public static final int GREATER = 57;
  public static final int DOBLEQUOTE = 44;
  public static final int LESS = 58;
  public static final int MINUS = 47;
  public static final int FOR = 30;
  public static final int FONTFAMILY = 25;
  public static final int DATA = 2;
  public static final int SEMICOLON = 36;
  public static final int POINTS = 6;
  public static final int LESSEQUAL = 60;
  public static final int COMMA = 35;
  public static final int Xaxis = 10;
  public static final int DIV = 54;
  public static final int DIFFERENT = 56;
  public static final int DIGIT = 61;
  public static final int PLUS = 46;
  public static final int ASSIGN = 52;
  public static final int SINGLEQUOTE = 45;
  public static final int BACKGROUNDCOLOR = 24;
  public static final int IF = 28;
  public static final int FONTSIZE = 26;
  public static final int CLOSEPARENTHESIS = 43;
  public static final int EOF = 0;
  public static final int LINK = 18;
  public static final int NUMBSIZE = 66;
  public static final int SIZE = 15;
  public static final int TRUE = 33;
  public static final int error = 1;
  public static final int MUL = 53;
  public static final int CLOSEBRACKET = 39;
  public static final int DOBLEDOT = 37;
  public static final int NUMBER = 62;
  public static final int TITTLE = 5;
  public static final int ICON = 17;
  public static final int NAME = 4;
  public static final int COLOR = 9;
  public static final int GREATEREQUAL = 59;
  public static final int HEADER = 22;
  public static final int OPENPARENTHESIS = 42;
  public static final int DOWHILE = 32;
  public static final int ELSE = 29;
  public static final int LETTER = 63;
  public static final int OPENBRACKET = 38;
  public static final int WHILE = 31;
  public static final int CLOSEBRACE = 41;
  public static final int XAXISLABEL = 13;
  public static final int COPYRIGHT = 27;
  public static final int FOOTER = 23;
  public static final int LINESTYLE = 19;
  public static final int SUM = 50;
  public static final int OPENBRACE = 40;
  public static final int STRING = 64;
  public static final int VALUE = 7;
  public static final int FALSE = 34;
  public static final int LABEL = 8;
  public static final int SUB = 51;
  public static final int YAXISLABEL = 14;
  public static final int IDENTIFIER = 67;
}

